name: Build & Push base-dev (multi-arch, native runners) - GHCR

on:
  push:
    branches:
      - main
    paths:
      - "workspace-images/base-dev/**"
      - ".github/workflows/build-base-dev.yaml"
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-image.yaml
    with:
      image_namespace: workspace-images
      image_name: base-dev
      dockerfile: workspace-images/base-dev/Dockerfile
    permissions:
      contents: read
      packages: write
