name: Build & Push python-dev (multi-arch, native runners) - GHCR

on:
  push:
    branches:
      - main
    paths:
      - "workspace-images/python-dev/**"
      - "workspace-images/shared/**"
      - ".github/workflows/build-python-dev.yaml"
  workflow_dispatch:
  workflow_run:
    workflows: ["Build & Push base-dev (multi-arch, native runners) - GHCR"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    uses: ./.github/workflows/build-image.yaml
    with:
      image_namespace: workspace-images
      image_name: python-dev
      dockerfile: workspace-images/python-dev/Dockerfile
    permissions:
      contents: read
      packages: write
