name: Build & Push nextjs-dev (multi-arch, native runners) - GHCR

on:
  push:
    branches:
      - main
    paths:
      - "workspace-images/nextjs-dev/**"
      - ".github/workflows/build-nextjs-dev.yaml"
  workflow_dispatch:
  workflow_run:
    workflows: ["Build & Push base-dev (multi-arch, native runners) - GHCR"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    uses: ./.github/workflows/build-image.yaml
    with:
      image_namespace: workspace-images
      image_name: nextjs-dev
      dockerfile: workspace-images/nextjs-dev/Dockerfile
    permissions:
      contents: read
      packages: write
