name: Build & Push hapi-hub (multi-arch, native runners) - GHCR

on:
  push:
    branches:
      - main
    paths:
      - "workspace-images/hapi-hub/**"
      - ".github/workflows/build-hapi-hub.yaml"
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-image.yaml
    with:
      image_namespace: workspace-images
      image_name: hapi-hub
      dockerfile: workspace-images/hapi-hub/Dockerfile
    permissions:
      contents: read
      packages: write
